# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amlogic/gx-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter gxm gxl g12b,$(TARGET_AMLOGIC_SOC)),)

endif
